name: Tailscale + Run Python Counter

on:
  workflow_dispatch:

jobs:
  setup-tailscale-and-run:
    runs-on: windows-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download Tailscale installer
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"

      - name: Install Tailscale (silent)
        shell: pwsh
        run: |
          Start-Process -FilePath ".\tailscale-setup.exe" -ArgumentList "/quiet" -Wait

      - name: Start Tailscale and connect
        shell: pwsh
        run: |
          $ts = 'C:\Program Files\Tailscale\tailscale.exe'
          if (-not (Test-Path $ts)) {
            Write-Error "tailscale.exe not found at expected path: $ts"
            exit 1
          }
          & $ts up --authkey $env:TAILSCALE_AUTHKEY --accept-routes --accept-dns

      - name: Run Python counter
        run: |
          python counter.py
